# 服务端口号
server:
  port: 9201

spring:
  application:
    name: mis-auth

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/isdp-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${secrets.mysql.username}
    password: ${secrets.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      keepalive-time: 30000
      validation-timeout: 3000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      password: ${secrets.redis.password}
      database: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: edu.scau.mis.common.domain
  configuration:
    map-underscore-to-camel-case: true