server:
  port: 8081



spring:
  application:
    name: mis-api
  config:
    import: file:D:/IDEA/workspace/demo/isdp/isdp-boot3Plus/config/secrets/application-secrets.yaml

  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
      poll-interval: 1000ms
      quiet-period: 400ms
    livereload:
      enabled: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/isdp-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${secrets.mysql.username}
    password: ${secrets.mysql.password}
    hikari:
      max-lifetime: 60000
      keepalive-time: 30000
      validation-timeout: 3000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      password: ${secrets.redis.password}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          max-wait: -1ms
          min-idle: 1
          time-between-eviction-runs: 10s

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: edu.scau.mis.common.domain
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: edu.scau.mis.web.controller

aliyun:
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: ${secrets.aliyun.oss.access-key-id}
    accessKeySecret: ${secrets.aliyun.oss.access-key-secret}
    bucketName: ${secrets.aliyun.oss.bucket-name}

logging:
  level:
    root: INFO
  file:
    name: isdp.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"