server:
  port: 8086

spring:
  application:
    name: mis-pay

  rabbitmq:
    host: ${MQ_HOST:rabbitmq}
    port: 5672
    username: ${secrets.rabbitmq.username}
    password: ${secrets.rabbitmq.password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/isdp-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${secrets.mysql.username}
    password: ${secrets.mysql.password}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 60000
      keepalive-time: 30000
      validation-timeout: 3000

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      password: ${secrets.redis.password}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          max-wait: -1ms
          min-idle: 1
          time-between-eviction-runs: 10s

mall:
  frontend-base-url: http://${SERVER_PUBLIC_IP}

alipay:
  app-id: "9021000159643102"
  private-key: ${secrets.alipay.private-key}
  public-key: ${secrets.alipay.public-key}
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  return-url: http://${SERVER_PUBLIC_IP}/api/pay/success
