server:
  port: 8080

spring:
  application:
    name: mis-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true
            max-age: 3600
        add-to-simple-url-handler-mapping: true

      routes:
        - id: mis-auth-route
          uri: lb://mis-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: mis-api-route
          uri: lb://mis-api
          predicates:
            - Path=/api/product/**,/api/category/**,/api/sale/**,/api/system/user/profile/**,/api/common/**,/api/,/api
          filters:
            - StripPrefix=1

        - id: mis-cart-route
          uri: lb://mis-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1

        - id: mis-order-route
          uri: lb://mis-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

        - id: mis-marketing-route
          uri: lb://mis-marketing
          predicates:
            - Path=/api/coupon/**
          filters:
            - StripPrefix=1

        - id: mis-pay-route
          uri: lb://mis-pay
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1

        - id: mis-ai-route
          uri: lb://mis-ai
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1